# Generated by Django 5.0.3 on 2024-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="team",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="info",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
