# Generated by Django 5.0.3 on 2024-05-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_info_team_alter_info_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="events",
            field=models.JSONField(default={}),
        ),
    ]
