# Generated by Django 5.0.3 on 2024-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_info_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="meets",
            field=models.JSONField(default=dict),
        ),
    ]
