# Generated by Django 5.0.3 on 2024-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_info_meets"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="pbs",
            field=models.JSONField(default=dict),
        ),
    ]
