# Generated by Django 5.0.3 on 2024-06-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_info_pbs"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="best_performances",
            field=models.JSONField(default=dict),
        ),
    ]
