# Generated by Django 5.0.3 on 2024-06-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_info_best_performances"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="goals",
            field=models.JSONField(default=dict),
        ),
    ]
